apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rene-deployment
  labels:
    app: rene
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: rene
  template:
    metadata:
      labels:
        app: rene
    spec:
      containers:
      - name:  rene-deployment-container
        image: mlrene/carvilla_image:v1.0
        ports:
        - containerPort: 80