apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-deployment
  labels:
    app:  nginx-deployment
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app:  nginx-deployment
    spec:
      containers:
      - name:  nginx-deployment
        image: nginx:latest 
        ports:
        - containerPort:  80