apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rc
  labels:
    app: nginx-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx-rs
        image: nginx-latest
